# Generated by Django 2.2.7 on 2019-11-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('user_passwordhash', models.CharField(max_length=100)),
                ('user_isadmin', models.BinaryField(default=b'0')),
                ('user_classroom_id', models.IntegerField(default=0)),
            ],
        ),
    ]
