# Generated by Django 2.2.7 on 2019-11-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='fav_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
